# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLik_cpp <- function(psi, p, Y, missing, non_det) {
    .Call(`_MiLinOccu_logLik_cpp`, psi, p, Y, missing, non_det)
}

getpsi <- function(Designs, betas, alpha, n_site, G) {
    .Call(`_MiLinOccu_getpsi`, Designs, betas, alpha, n_site, G)
}

getp <- function(Designs_det, betas_det, alpha, n_period, n_site, G) {
    .Call(`_MiLinOccu_getp`, Designs_det, betas_det, alpha, n_period, n_site, G)
}

